### ISSUE TITLE
137pg 오탈자

### ISSUE THREAD

**Issue by Cho-D-YoungRae** [rickiepark/hg-mldl#1]
137pg의 가장 아래 손코딩 박스 위

`(50, 15*39-709)` -> `(50, 50*39-709)`

로 변경되어야 될 것 같습니다. 검토해주시면 감사드리겠습니다.

**Comment by rickiepark** [comment]
앗... 그러네요. ㅠ.ㅠ
에러타를 찾아 주셔서 감사드립니다.
중쇄 때 수정해서 반영하겠습니다.
감사합니다! :)

**Comment by rickiepark** [comment]
다른 에러타는 https://tensorflow.blog/hg-mldl/ 에 정리되어 있습니다. 꼭 참고해 주세요! :)
