### ISSUE TITLE
6-2 k평균 (p.305~)

### ISSUE THREAD

**Issue by Jhsysng** [rickiepark/hg-mldl#2]
p.305,6부터 사용하는
km.labels_에서 값이 책과 다르게 앞뒤 대칭으로 들어갑니다.
이후 실행에는 문제가 없지만 결과가 다르게 나옵니다.
레포지토리 코드도 동일하여 코멘트 남깁니다.

**Comment by rickiepark** [comment]
안녕하세요. 책에 설명되어 있듯이 군집에서 클러스터 레이블은 아무런 의미가 없습니다. 사이킷런 버전에 따라 레이블이 다른 순서로 매겨질 수 있습니다. 감사합니다.
